# docker run --name api-solid-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=apisolid -p 5432:5432 bitnami/postgresql
version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: apisolid
    ports:
      - 5432:5432
